# Generated by Django 3.2.6 on 2022-10-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('is_private', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
