# Generated by Django 3.2.6 on 2022-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
